version: '3.2'

services:
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=thenewboston_pv
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - C_FORCE_ROOT=true
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./scripts/docker_entrypoints/initdb.d:/docker-entrypoint-initdb.d

  pv:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_APPLICATION_ENVIRONMENT=local
      - NETWORK_SIGNING_KEY=d73da3e068e55aba408d99a4a04b0db9edf6a134fbec0acb5ff6ffa1f41e1b04
      - NODE_IDENTIFIER=1488799e04b00951e4c10f20a15e13912aee504b831a7a1cd19d4b1db7ff9266
      - ACCOUNT_NUMBER=6e3232cb30bdcb79494ca9c1993dfbe6845a2f079438a7d56502f94fbd64bb2b
      - NODE_PORT=8001
      - REDIS_DB=0
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=thenewboston_pv
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - SECRET_KEY=somesecret
    env_file:
      - .env
    entrypoint: /opt/project/scripts/docker_entrypoints/entrypoint_pv.sh
    volumes:
      - .:/opt/project
      - ./media/pv:/opt/project/media
    ports:
      - 8001:8000
    links:
      - db
      - redis
    depends_on:
      - db
      - redis

  cv1:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_APPLICATION_ENVIRONMENT=local
      - NETWORK_SIGNING_KEY=4a0a0ad6a33df956ae450884a1cc606d8ac7698c34bbc771c7ca87ba9adca2a5
      - NODE_IDENTIFIER=eade0f962092e2086ede39c351e0f9ce8d5fc0b040eb90dfb83010b433d5b1af
      - ACCOUNT_NUMBER=5e76c46de6256db3987de8d78ef4af8d792979a95fdd1094bcad3e00c82d0e08
      - NODE_PORT=8002
      - REDIS_DB=1
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=thenewboston_cv1
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - SECRET_KEY=somesecret
    env_file:
      - .env
    entrypoint: /opt/project/scripts/docker_entrypoints/entrypoint_cv.sh
    volumes:
      - .:/opt/project
      - ./media/cv1:/opt/project/media
    ports:
      - 8002:8000
    links:
      - pv
      - db
      - redis
    depends_on:
      - pv
      - db
      - redis

  cv2:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_APPLICATION_ENVIRONMENT=local
      - NETWORK_SIGNING_KEY=ecaf0f00cdc9c00d1621e86b49dfba186d20510b08ffc71fdbd9af3cdb3fb86c
      - NODE_IDENTIFIER=37401d1ff1dccb96f257a868011507758a39f7c1504280e863043a4cca4548f6
      - ACCOUNT_NUMBER=755ba2840909ae88987ef9de08dc5882ffa1e3df774e95a9500f5a9cfb4fe0be
      - NODE_PORT=8003
      - REDIS_DB=2
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=thenewboston_cv2
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - SECRET_KEY=somesecret
    env_file:
      - .env
    entrypoint: /opt/project/scripts/docker_entrypoints/entrypoint_cv.sh
    volumes:
      - .:/opt/project
      - ./media/cv2:/opt/project/media
    ports:
      - 8003:8000
    links:
      - pv
      - db
      - redis
    depends_on:
      - pv
      - db
      - redis

  bank:
    image: docker.pkg.github.com/thenewboston-developers/bank/bank:latest
    environment:
      - DJANGO_APPLICATION_ENVIRONMENT=local
      - NETWORK_SIGNING_KEY=c71e496b66df1efdacc2fc4fab5c9c1a5b0551ebb56ea2a4987378e7ff6e1ed5
      - NODE_IDENTIFIER=c292c7c13c46e0abcb6c84b1f35a24efb5dd4605445a2864754e02f174b2a192
      - ACCOUNT_NUMBER=7bb9787dec7ee1978b43c182e554e5e5e62627e80f3fa6681e7f983930dbb1be
      - NODE_PORT=8004
      - REDIS_DB=3
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=thenewboston_bank
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - SECRET_KEY=somesecret
    env_file:
      - .env
    entrypoint: /opt/project/scripts/docker_entrypoints/entrypoint.sh
    ports:
      - 8004:8000
    links:
      - pv
      - db
      - redis
    depends_on:
      - pv
      - db
      - redis

  celery_pv:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_APPLICATION_ENVIRONMENT=local
      - NETWORK_SIGNING_KEY=d73da3e068e55aba408d99a4a04b0db9edf6a134fbec0acb5ff6ffa1f41e1b04
      - REDIS_DB=0
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=thenewboston_pv
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - SECRET_KEY=somesecret
    command: celery -A config.settings worker -l debug -Q celery,block_queue,confirmation_block_queue
    volumes:
      - .:/opt/project
    links:
      - pv
      - db
      - redis
    depends_on:
      - db
      - redis

  celery_cv1:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_APPLICATION_ENVIRONMENT=local
      - NETWORK_SIGNING_KEY=4a0a0ad6a33df956ae450884a1cc606d8ac7698c34bbc771c7ca87ba9adca2a5
      - REDIS_DB=1
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=thenewboston_cv1
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - SECRET_KEY=somesecret
    command: celery -A config.settings worker -l debug -Q celery,block_queue,confirmation_block_queue
    volumes:
      - .:/opt/project
    links:
      - cv1
      - db
      - redis
    depends_on:
      - db
      - redis

  celery_cv2:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DJANGO_APPLICATION_ENVIRONMENT=local
      - NETWORK_SIGNING_KEY=ecaf0f00cdc9c00d1621e86b49dfba186d20510b08ffc71fdbd9af3cdb3fb86c
      - REDIS_DB=2
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=thenewboston_cv2
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - SECRET_KEY=somesecret
    command: celery -A config.settings worker -l debug -Q celery,block_queue,confirmation_block_queue
    volumes:
      - .:/opt/project
    links:
      - cv2
      - db
      - redis
    depends_on:
      - db
      - redis

  celery_bank:
    image: docker.pkg.github.com/thenewboston-developers/bank/bank:latest
    environment:
      - DJANGO_APPLICATION_ENVIRONMENT=local
      - NETWORK_SIGNING_KEY=c71e496b66df1efdacc2fc4fab5c9c1a5b0551ebb56ea2a4987378e7ff6e1ed5
      - REDIS_DB=3
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_DB=thenewboston_bank
      - POSTGRES_USER=thenewboston
      - POSTGRES_PASSWORD=thenewboston
      - SECRET_KEY=somesecret
    command: celery -A config.settings worker -l debug
    links:
      - bank
      - db
      - redis
    depends_on:
      - db
      - redis

volumes:
  postgresql-data:
    driver: local

  redis-data:
    driver: local
